#                                            $$ Titanic$$$$ Case$$$$ Study $$

In this case study we need to identify the probability of variaous dependent variables in dataset with respect to other independent variable

In [89]:
#importing important libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

# Loading titanic dataset

In [90]:
dataset=pd.read_csv("train.csv")

In [91]:
dataset.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [92]:
dataset.shape

(889, 12)

# Checking for null values in dataset

In [93]:
dataset.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64

### more no. of null values pressent in column Cabin 
### therefore,, we can drop this entire column

In [94]:
del dataset["Cabin"]

In [95]:
dataset.head(1)

PassengerId  Survived  Pclass                     Name   Sex   Age  SibSp  \
0            1         0       3  Braund, Mr. Owen Harris  male  22.0      1   

   Parch     Ticket  Fare Embarked  
0      0  A/5 21171  7.25        S

### Now drop unwanted columns that are irrelevant 

In [96]:
dataset.drop(["PassengerId","Name","Ticket"],axis=1,inplace=True)

In [97]:
dataset.head(1)

Survived  Pclass   Sex   Age  SibSp  Parch  Fare Embarked
0         0       3  male  22.0      1      0  7.25        S

In [98]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 889 entries, 0 to 888
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  889 non-null    int64  
 1   Pclass    889 non-null    int64  
 2   Sex       889 non-null    object 
 3   Age       889 non-null    float64
 4   SibSp     889 non-null    int64  
 5   Parch     889 non-null    int64  
 6   Fare      889 non-null    float64
 7   Embarked  889 non-null    object 
dtypes: float64(2), int64(4), object(2)
memory usage: 55.7+ KB


# Convert text data into numeriacl data

In [99]:
from sklearn.preprocessing import LabelEncoder
lab=LabelEncoder()

dataset.Sex=lab.fit_transform(dataset.Sex)
dataset.Embarked=lab.fit_transform(dataset.Embarked)

In [100]:
dataset.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         0       3    1  22.0      1      0   7.2500         2
1         1       1    0  38.0      1      0  71.2833         0
2         1       3    0  26.0      0      0   7.9250         2
3         1       1    0  35.0      1      0  53.1000         2
4         0       3    1  35.0      0      0   8.0500         2

In [101]:
dataset.columns

Index(['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare',
       'Embarked'],
      dtype='object')

# Support Vector Machine

In [102]:
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score,confusion_matrix
clf=svm.SVC(gamma=0.01,C=100)
l1=list()
l2=list()

In [103]:
def supvec(i):
    
    for j in i:
        print("Here '{}' is dependent variable and remaining are independent variable \n".format(j))
        y=dataset[j]
        print("Y = \n",y.head())
        x=dataset.drop(j,axis=1)
        print("X = \n",x.head())
        x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)
        clf.fit(x_train,y_train)
        ypred=clf.predict(x_test)
        acc=accuracy_score(y_test,ypred,normalize=True)
        print("Accuracy score when '{}' is dependent variable is {} \n ".format(j,acc))
        conf=confusion_matrix(y_test,ypred)
        print("Confusion matrix when '{}' is dependent variable is\n {} \n\n".format(j,conf))
        l1.append(j)
        l2.append(acc)
        print("*"*100)
    df=pd.DataFrame({"Dependent Variables":l1,"Accuracy Score":l2})
    print(df)
        
        
        
        

In [104]:
supvec(['Survived', 'Pclass', 'Sex', 'SibSp', 'Parch','Embarked'])

Here 'Survived' is dependent variable and remaining are independent variable 

Y = 
 0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64
X = 
    Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0       3    1  22.0      1      0   7.2500         2
1       1    0  38.0      1      0  71.2833         0
2       3    0  26.0      0      0   7.9250         2
3       1    0  35.0      1      0  53.1000         2
4       3    1  35.0      0      0   8.0500         2
Accuracy score when 'Survived' is dependent variable is 0.7415730337078652 
 
Confusion matrix when 'Survived' is dependent variable is
 [[124  33]
 [ 36  74]] 


****************************************************************************************************
Here 'Pclass' is dependent variable and remaining are independent variable 

Y = 
 0    3
1    1
2    3
3    1
4    3
Name: Pclass, dtype: int64
X = 
    Survived  Sex   Age  SibSp  Parch     Fare  Embarked
0         0    1  22.0      1      0   7.2500     

# Result:
#### "Pclass is giving high accuracy score than others.
    