# 1. Create a 3x3x3 array with random values

In [9]:
from numpy import random

x=random.randint(100, size=(3,3,3))

print(x)

[[[31 91 39]
  [33 88 77]
  [60 72 44]]

 [[58 37 71]
  [65 10 94]
  [73 70 94]]

 [[81 35 24]
  [72 19 26]
  [17 21 80]]]


In [10]:
x.ndim

3

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [13]:
x= np.diag(np.arange(1,5), k = -1)
print (x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern¶


In [14]:
Z = np.zeros ((8,8), dtype=int)
Z[1::2, ::2]= 1
Z[::2, 1::2] = 1
print (Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# Normalize a 5x5 random matrix

In [15]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z= (Z-Zmin)/(Zmax-Zmin)
print (Z)

[[0.66106522 0.22931981 0.82640581 0.61537771 0.02015759]
 [0.37355201 0.42993473 0.41692466 0.44969995 0.28859636]
 [0.2812938  0.96229476 0.37004734 1.         0.12089077]
 [0.3213195  0.64006659 0.         0.07826048 0.34189431]
 [0.99106124 0.42030032 0.72802389 0.38722181 0.47936153]]


# 5. How to find common values between two arrays?¶


In [17]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))


Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


# 6.How to get the dates of yesterday, today and tomorrow?¶


In [18]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-25
Today:  2020-07-26
Tomorrow:  2020-07-27


# 7. Consider two random array A and B, check if they are equal¶


In [23]:
import numpy as np
A = np.random.randint(0,2,6)
print("First array:")
print(x)
B = np.random.randint(0,2,6)
print("Second array:")
z=np.array_equal(A,B)
if z==True:
    print("arrays are equal")
else:
    print("arrays are not equal")

First array:
[0 0 0 1 1 1]
Second array:
arrays are not equal


# 8.Create random vector of size 10 and replace the maximum value by 0¶


In [29]:
arr=random.random(10)
print(arr)
x=np.max(arr)
arr[arr==x]=0
arr


[0.28679722 0.23848781 0.19198276 0.65593302 0.22692764 0.8660251
 0.33834607 0.02024869 0.10924884 0.40978218]


array([0.28679722, 0.23848781, 0.19198276, 0.65593302, 0.22692764,
       0.        , 0.33834607, 0.02024869, 0.10924884, 0.40978218])

# 9. How to print all the values of an array?¶
 

In [34]:
arr=random.random((3,3))
arr

array([[0.33078649, 0.06836614, 0.6063472 ],
       [0.87824893, 0.50746813, 0.93542322],
       [0.89965942, 0.03816415, 0.7713462 ]])

In [36]:
for i in np.nditer(arr):
    print(i)

0.33078649268277793
0.06836613621541066
0.60634720113589
0.8782489257993217
0.5074681263964523
0.9354232174560292
0.8996594154032629
0.0381641512910581
0.771346202243442


# 10.Subtract the mean of each row of a matrix

In [45]:
import numpy as np
print("Original matrix:\n")
X = np.random.rand(5, 10)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.41268937 0.82150195 0.04496513 0.79832998 0.10992519 0.93508237
  0.18757173 0.63639035 0.60130842 0.90934586]
 [0.36486543 0.73810066 0.10448811 0.02811958 0.44083832 0.46733904
  0.93501945 0.39489823 0.61890705 0.21906823]
 [0.98348461 0.9025094  0.45248893 0.34728417 0.46527102 0.82050162
  0.50070284 0.06988882 0.41293978 0.74311602]
 [0.12606004 0.10853716 0.04381489 0.13344897 0.29241032 0.65913458
  0.75193119 0.18115098 0.58845229 0.04441257]
 [0.58166046 0.87291221 0.88917747 0.47432379 0.04470523 0.93503164
  0.89431073 0.39531251 0.79602448 0.67565537]]

Subtract the mean of each row of the said matrix:

[[-1.33021662e-01  2.75790910e-01 -5.00745904e-01  2.52618948e-01
  -4.35785844e-01  3.89371333e-01 -3.58139307e-01  9.06793136e-02
   5.55973860e-02  3.63634827e-01]
 [-6.62989840e-02  3.06936254e-01 -3.26676303e-01 -4.03044830e-01
   9.67391231e-03  3.61746294e-02  5.03855042e-01 -3.62661802e-02
   1.87742642e-01 -2.12096182e-01]
 [ 4.13665892e-01  3

In [44]:
x-np.mean(x,axis=1)

ValueError: operands could not be broadcast together with shapes (3,5) (3,) 

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?¶


In [46]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[3. 2. 2. 5. 2. 5. 2. 3. 4. 2.]


# 12.How to get the diagonal of a dot product?¶


In [47]:
a = np.random.randint(0,10,(2,2))
b= np.random.randint(0,10,(2,2))

print(a)
print(b)

np.diag(np.dot(a, b))

[[3 2]
 [1 8]]
[[1 4]
 [1 6]]


array([ 5, 52])

# 13.How to find the most frequent value in an array?¶


In [48]:

a = np.random.randint(1,10,15)
print(a)
# print(np.bincount(a))
np.bincount(a).argmax()

[5 5 6 3 8 2 2 7 1 3 7 7 7 7 5]


7

# 14.How to get the n largest values of an array?


In [50]:

a = np.arange(100)
np.random.shuffle(a)
n = 5


print (a[np.argpartition(-a,n)][:n])

[99 98 96 97 95]


# 15.How to create a record array from a regular array?


In [51]:
x1=np.array([1,2,3,4])
x2=np.array(['a','dd','xyz','12'])
x3=np.array([1.1,2,3,4])
r = np.core.records.fromarrays([x1,x2,x3],names='a,b,c')
print(r[1])

(2, 'dd', 2.)
